/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'save': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'generate': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'analyze': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'get-projects': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'delete-project': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'create-project': ApiRouteHandler<{ userId?: string; name: string; type: string; shapes?: unknown[] }, unknown, never>
    'convert-to-react': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'register-user': ApiRouteHandler<{ email: string; password: string }, unknown, never>
    'login-user': ApiRouteHandler<{ email: string; password: string }, unknown, never>
  }
}